#!/bin/bash

HASH="NULL"
SCRIPT_NAME="$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")"

if [ $# -eq 0 ]
then
  echo 'Resigns all commits from $HASH to current $HEAD'
  echo "Usage: ${SCRIPT_NAME} \$HASH"
else
  HASH="$1"
  git filter-branch -f --commit-filter 'git commit-tree -S "$@";' "${HASH}^1..HEAD"
fi
